baseURL = "http://jonatha.daguerre.com.br/"
title = "Jonatha Daguerre Vasconcelos"
theme = "hugo-initio"
publishDir = "docs"

[Languages]
[Languages.en]
    weight = 1

[Languages.pt]
    weight = 2

[params]
    name = "Jonatha Daguerre Vasconcelos"
    description = "Hacker Culture | Education | Coding"
    email = "jonatha@daguere.com.br"
    year = 2017
    background = ""
    favicon = "/images/favicon.ico"
    DateForm = "2/01/2006"

    showSubheader = false
    showServices = false
    showRecentWorks = false
    showDownload = false
    showClients = false
    footerEnableFormWidget = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false


    showPosts = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/posts/"
    weight = 2
[[Languages.pt.menu.main]]
    name = "blog"
    url = "/pt/posts/"
    weight = 2
[[Languages.pt.menu.main]]
    name = "home"
    url = "/pt"
    weight = 1

[[Languages.pt.menu.main]]
    name = "Como se Tornar um Hacker"
    url = "/hacker-howto"
    weight = 4
[[Languages.pt.menu.main]]
    name = "Glider: Um Emblema Hacker Universal"
    url = "/hacker-emblem"
    weight = 5
[[Languages.pt.menu.main]]
    name = "Projeto Pescar - GNU/Linux"
    url = "/pescar"
    weight = 6

[params.google.analytics]
    trackerID = "UA-100627479-1"

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/jonathadv"
    icon = "fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
    title = "linkedin"
    url = "https://www.linkedin.com/in/jonathadv"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
    title = "github"
    url = "https://github.com/jonathadv"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = "github"
[[params.social]]
    title = "stackoverflow"
    url = "http://stackoverflow.com/users/7254201/jonatha-daguerre"
    icon = "fa-stack-overflow"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
    title = "email"
    url = "mailto:jonatha@daguere.com.br"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"
[[params.social]]
    title = "lattes"
    url = "http://lattes.cnpq.br/2475560585762389"
    class = "fa-lattes lattes-icon fa-2"
    footer = true
    sharethis = true
    network = "lattes"
    comment_i18n = "lattes"

